export const services = [
 {slug:'ai-chatbots-virtual-agents',title:'AI agents & chatbots',short:'AI agents',summary:'Turn conversations into completed tasks.',description:'Conversational agents that answer customer questions, qualify leads, and take action across your business tools. Grounded in your knowledge, with clear boundaries and human handoffs.',steps:['Customer asks a question','Agent retrieves your knowledge','Your tools take action'],tags:['Knowledge-grounded answers','Lead qualification','Human handoff']},
 {slug:'workflow-automation',title:'Workflow automation',short:'Workflow automation',summary:'Less copy-paste. More forward motion.',description:'Connect the steps between your teams, apps, and data. We build multi-step workflows that handle routine operations, route exceptions, and keep the right people in the loop.',steps:['An event starts the workflow','Rules route the next step','Teams and systems stay in sync'],tags:['n8n orchestration','Approval workflows','Error recovery']},
 {slug:'data-pipeline-engineering',title:'Data pipeline engineering',short:'Data pipelines',summary:'Reliable data. Better decisions.',description:'Bring fragmented data into one dependable flow. We engineer ETL and ELT pipelines, reporting systems, and data infrastructure for timely operational visibility.',steps:['Collect events from your systems','Validate and transform records','Deliver decision-ready data'],tags:['ETL / ELT','PostgreSQL & Supabase','Real-time reporting']},
 {slug:'custom-ai-models',title:'Custom AI development',short:'Custom AI',summary:'Intelligence built around your business.',description:'Build domain-specific AI capabilities for your own documents, processes, and products—from intelligent extraction to tailored model development and evaluation.',steps:['Define the business task','Evaluate on your domain data','Deploy and measure performance'],tags:['Document intelligence','Model evaluation','Domain-specific AI']},
 {slug:'ai-system-integration',title:'AI system integration',short:'System integration',summary:'Your existing tools. Working together.',description:'Embed AI and automation into your CRM, ERP, and internal software. Connect your systems of record through APIs and carefully scoped permissions.',steps:['Connect your existing tools','Add an intelligence layer','Update systems with traceability'],tags:['CRM & ERP','API integrations','Access controls']},
 {slug:'ai-audit-optimization',title:'AI audit & optimization',short:'Audit & optimization',summary:'Find the work worth automating.',description:'Review your operations, uncover bottlenecks, and prioritize practical automation opportunities. Improve the reliability and cost of systems you already run.',steps:['Map your current operations','Prioritize by impact and effort','Create an actionable roadmap'],tags:['Operational audit','ROI planning','Performance tuning']}
];
export const projects=[
 {slug:'autonomous-multi-channel-support-lead-routing',client:'OmniRetail Global',category:'E-commerce & retail',title:'Customer support. Without the bottleneck.',fullTitle:'Autonomous Multi-Channel Support & Intelligent Lead Routing',summary:'An AI support system that handles routine questions and routes the conversations that need a human.',metric:'68%',label:'Tier-1 support deflection',secondary:'12 sec',secondaryLabel:'Average first response',image:'retail',service:'AI agents',challenge:'A high volume of order tracking, returns, and product questions was slowing down customer support.',solution:'A knowledge-grounded AI agent connects customer conversations to commerce tools, automates routine resolutions, and hands exceptions to the support team.',stack:['n8n','Claude','Shopify','Supabase']},
 {slug:'intelligent-document-processing-financial-reconciliation',client:'Apex FinServe',category:'Fintech & corporate finance',title:'From paperwork to possibility.',fullTitle:'Intelligent Document Processing & Automated Financial Reconciliation',summary:'Invoice extraction, multi-currency verification, and ledger reconciliation in one connected workflow.',metric:'99.4%',label:'Extraction accuracy',secondary:'4.1 sec',secondaryLabel:'Processing time',image:'finance',service:'Workflow automation',challenge:'Manual invoice processing and financial reconciliation created repetitive work and opportunities for error across 45,000 monthly invoices.',solution:'An automated document pipeline extracts invoice fields, verifies financial data, and connects reconciliation steps to the ledger, with exceptions routed for review.',stack:['Document AI','Python','PostgreSQL','n8n']},
 {slug:'real-time-etl-automated-supply-chain-analytics',client:'Nexus Logistics Partners',category:'Logistics & supply chain',title:'A clearer view of every move.',fullTitle:'Real-Time Enterprise ETL & Automated Supply Chain Analytics',summary:'A resilient data pipeline connecting operational events, anomaly detection, and supply-chain analytics.',metric:'15M+',label:'Daily event records',secondary:'99.98%',secondaryLabel:'Pipeline uptime',image:'logistics',service:'Data pipelines',challenge:'High-volume logistics events were fragmented across operational systems, limiting timely visibility into the supply chain.',solution:'An enterprise ETL pipeline brings event data together, detects anomalies, and supports predictive rerouting and operational reporting.',stack:['Python','Kafka','PostgreSQL','Analytics']}
];
export const articles=[
 {slug:'framework-calculating-operational-automation-roi',category:'Strategy',title:'A practical framework for automation ROI',description:'Turn time saved, fewer errors, and faster operations into a clear business case.',date:'August 20, 2026',time:'5 min read',sections:[['Start with the workflow','Map the task as it runs today: who performs it, how often it occurs, the tools involved, and where exceptions arise. A clear baseline is more useful than an ambitious estimate.'],['Measure the full cost','Estimate staff time, rework, delays, and operational costs. Separate hard savings from capacity freed for other work. An hour saved does not always translate directly into a cash saving.'],['Compare value with ongoing cost','Include implementation, software, model usage, maintenance, and human review. Compare a conservative benefit estimate against those costs and define how you will measure the result.'],['Validate with a focused pilot','Choose a bounded workflow, test it with representative data, and measure the difference against your baseline before expanding.']]},
 {slug:'building-resilient-data-pipelines-real-time-ai',category:'Data engineering',title:'Better AI starts with a resilient data pipeline',description:'Why clean inputs, recovery paths, and observability matter as much as the model.',date:'August 18, 2026',time:'8 min read',sections:[['Treat data as a product','Define the expected schema, freshness, ownership, and quality of every source. Make those expectations visible to the teams using the data.'],['Design for failure','Use retries with limits, idempotent writes, and a queue for failed events. A malformed record should not stop the entire system.'],['Monitor the whole journey','Track volume, delay, errors, and data quality from ingestion through delivery. Alert on changes that affect the business, and document a recovery process.'],['Keep evolution safe','Version schemas and test changes against downstream consumers. Reliable AI depends on data that remains understandable as your systems change.']]},
 {slug:'why-custom-ai-agents-beat-off-the-shelf-chatbots',category:'AI agents',title:'When your business needs more than a chatbot',description:'From answering questions to completing useful work across your systems.',date:'August 14, 2026',time:'6 min read',sections:[['Start with the job','A simple FAQ bot may be enough for basic information. A custom agent becomes useful when it needs your business context, tool access, or a multi-step process.'],['Ground answers in your knowledge','Connect approved content and define how the agent behaves when it lacks evidence. Keep knowledge current and provide a clear route to a human.'],['Give tools narrow permissions','An agent that changes records needs explicit permissions, validation, and logs. Add approval steps for actions that should remain under human control.'],['Evaluate outcomes','Test realistic conversations and edge cases. Measure successful task completion, handoff quality, and customer experience, alongside response speed.']]}
];
export const faqs=[['What can Prime Automation build?','We build AI agents and chatbots, multi-step workflow automations, data pipelines, custom AI systems, and integrations with your existing tools. We also audit and optimize systems you already have.'],['Can you work with our existing software?','Yes. We start with your current CRM, ERP, databases, and internal tools. Where APIs or supported integrations are available, we connect them rather than asking your team to replace its entire stack.'],['How long does an automation project take?','Timing depends on the workflow, integrations, data quality, and review requirements. The audit defines a focused scope and delivery plan before implementation begins.'],['How do you handle security and human oversight?','We design around scoped access, validated inputs, traceable actions, and human approval where needed. Specific data handling and deployment requirements are agreed during discovery.'],['What happens during the free audit?','In a 45-minute conversation, we review your workflow, identify bottlenecks, and discuss automation opportunities. You get a practical starting point for deciding what to build.'],['Do you support systems after launch?','Monitoring, maintenance, and ongoing optimization can be included in the project scope. We define ownership, support expectations, and success measures before deployment.']];
